# Generated by Django 4.2.15 on 2024-09-02 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='users/',
                verbose_name='аватар',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={
                    'unique': 'Пользователь с таким именем уже существует.'
                },
                help_text='Обязательное поле. 150 символов или меньше. Только буквы, цифры и ^[\\w.@+-]+\\Z символы.',
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Имя пользователя может содержать только буквы, цифры и ^[\\w.@+-]+\\Z символы.',
                        regex='^[\\w.@+-]+\\Z',
                    )
                ],
                verbose_name='Имя пользователя',
            ),
        ),
    ]
